### ISSUE TITLE
About multiprocessing

### ISSUE THREAD

**Issue by NititOrz** [rkcosmos/deepcut#21]
I tried using multiprocessing with asynchronous and it got infinity loop or something. Program is not processed. Here is sample

    from multiprocessing import Pool
    import deepcut as dc

    def f(text):
        return dc.tokenize(text)

    if __name__ == '__main__':
        texts = ["ง่ายๆแค่นี้เอง", "ลองใหม่สิ", "เอางี้นะ", "เอาอีกรอบหนึ่ง"]
        pool = Pool(processes=4)

        multiple_results = [pool.apply_async(f, (i,)) for i in texts]
        for func in multiple_results:
             print(func.get())

I opened the Activity Monitor on macOS and it's not used the processor.
It happened after the updated version that making your program faster. I think.

**Comment by titipata** [comment]
Hi @NititOrz, can you try following [this example from Stack Overflow](https://stackoverflow.com/questions/42504669/keras-tensorflow-and-multiprocessing-in-python)? I think you have to import `keras` for each workers in order to make it `multiprocessing`. Something as following would work.

```python
from multiprocessing import Pool
def _tokenizing(text):
    import deepcut # import here
    return deepcut.tokenize(text)

texts = ["ง่ายๆแค่นี้เอง", "ลองใหม่สิ", "เอางี้นะ", "เอาอีกรอบหนึ่ง"]
pool = Pool(processes=4)

multiple_results = [pool.apply_async(_tokenizing, (i,)) for i in texts]
for func in multiple_results:
     print(func.get())
```

PS. you can tag me next time too. I sometimes didn't check the library that often.

**Comment by NititOrz** [comment]
@titipata Thank you.
